// AUTOGENERATED. Run generator/main.py to regenerate
#ifndef __MCP_FROM_TOP_H
#define __MCP_FROM_TOP_H

#include "MCP_Ack.h"
#include "MCP_Reboot.h"
#include "MCP_AreYouAlive.h"
#include "MCP_DribblerCommand.h"
#include "MCP_KickerCharge.h"
#include "MCP_KickerStopCharge.h"
#include "MCP_Kick.h"
#include "MCP_Chip.h"
#include "MCP_Kill.h"
#include "MCP_StopSending.h"
#endif /* __MCP_FROM_TOP_H */
