// AUTOGENERATED. Run generator/main.py to regenerate
/*

*/

#ifndef __MCP_KICKER_STOP_CHARGE_H
#define __MCP_KICKER_STOP_CHARGE_H

#include <stdbool.h>
#include <stdint.h>
#include "MCP_BaseTypes.h"

typedef struct _MCP_KickerStopChargePayload {
    uint8_t payload[MCP_PACKET_SIZE_MCP_KICKER_STOP_CHARGE];
} MCP_KickerStopChargePayload;

typedef struct _MCP_KickerStopCharge {
} MCP_KickerStopCharge;

// ================================ GETTERS ================================
// ================================ SETTERS ================================
// ================================ ENCODE ================================
static inline void encodeMCP_KickerStopCharge(MCP_KickerStopChargePayload *mcpkscp, MCP_KickerStopCharge *mcpksc){
}

// ================================ DECODE ================================
static inline void decodeMCP_KickerStopCharge(MCP_KickerStopCharge *mcpksc, MCP_KickerStopChargePayload *mcpkscp){
}

#endif /*__MCP_KICKER_STOP_CHARGE_H*/
