// AUTOGENERATED. Run generator/main.py to regenerate
/*
[  0   ]
1111---- mcpVersion
----1--- sensorWorking
*/

#ifndef __MCP_POWER_ALIVE_H
#define __MCP_POWER_ALIVE_H

#include <stdbool.h>
#include <stdint.h>
#include "MCP_BaseTypes.h"

typedef struct _MCP_PowerAlivePayload {
    uint8_t payload[MCP_PACKET_SIZE_MCP_POWER_ALIVE];
} MCP_PowerAlivePayload;

typedef struct _MCP_PowerAlive {
    uint32_t   mcpVersion          ; // integer [0, 15]              version of mcp
    bool       sensorWorking       ; // integer [0, 1]               voltage sensor working
} MCP_PowerAlive;

// ================================ GETTERS ================================
static inline uint32_t MCP_PowerAlive_get_mcpVersion(MCP_PowerAlivePayload *mcppap){
   return ((mcppap->payload[0] & 0b11110000) >> 4);
}

static inline bool MCP_PowerAlive_get_sensorWorking(MCP_PowerAlivePayload *mcppap){
    return (mcppap->payload[0] & 0b00001000) > 0;
}

// ================================ SETTERS ================================
static inline void MCP_PowerAlive_set_mcpVersion(MCP_PowerAlivePayload *mcppap, uint32_t mcpVersion){
    mcppap->payload[0] = ((mcpVersion << 4) & 0b11110000) | (mcppap->payload[0] & 0b00001111);
}

static inline void MCP_PowerAlive_set_sensorWorking(MCP_PowerAlivePayload *mcppap, bool sensorWorking){
    mcppap->payload[0] = ((sensorWorking << 3) & 0b00001000) | (mcppap->payload[0] & 0b11110111);
}

// ================================ ENCODE ================================
static inline void encodeMCP_PowerAlive(MCP_PowerAlivePayload *mcppap, MCP_PowerAlive *mcppa){
    MCP_PowerAlive_set_mcpVersion          (mcppap, mcppa->mcpVersion);
    MCP_PowerAlive_set_sensorWorking       (mcppap, mcppa->sensorWorking);
}

// ================================ DECODE ================================
static inline void decodeMCP_PowerAlive(MCP_PowerAlive *mcppa, MCP_PowerAlivePayload *mcppap){
    mcppa->mcpVersion    = MCP_PowerAlive_get_mcpVersion(mcppap);
    mcppa->sensorWorking = MCP_PowerAlive_get_sensorWorking(mcppap);
}

#endif /*__MCP_POWER_ALIVE_H*/
