// AUTOGENERATED. Run generator/main.py to regenerate
#ifndef __MCP_FROM_POWER_H
#define __MCP_FROM_POWER_H

#include "MCP_Ack.h"
#include "MCP_PowerAlive.h"
#include "MCP_PowerVoltage.h"
#endif /* __MCP_FROM_POWER_H */
