// AUTOGENERATED. Run generator/main.py to regenerate
/*
[  0   ]
11111111 voltagePowerBoard
*/

#ifndef __MCP_POWER_VOLTAGE_H
#define __MCP_POWER_VOLTAGE_H

#include <stdbool.h>
#include <stdint.h>
#include "MCP_BaseTypes.h"

typedef struct _MCP_PowerVoltagePayload {
    uint8_t payload[MCP_PACKET_SIZE_MCP_POWER_VOLTAGE];
} MCP_PowerVoltagePayload;

typedef struct _MCP_PowerVoltage {
    float      voltagePowerBoard   ; // float   [20.000, 30.000]     power board voltage
} MCP_PowerVoltage;

// ================================ GETTERS ================================
static inline float MCP_PowerVoltage_get_voltagePowerBoard(MCP_PowerVoltagePayload *mcppvp){
    uint32_t _voltagePowerBoard = ((mcppvp->payload[0]));
    return (_voltagePowerBoard * 0.0392156862745098F) + 20.0000000000000000F;
}

// ================================ SETTERS ================================
static inline void MCP_PowerVoltage_set_voltagePowerBoard(MCP_PowerVoltagePayload *mcppvp, float voltagePowerBoard){
    uint32_t _voltagePowerBoard = (uint32_t)((voltagePowerBoard -20.0000000000000000F) / 0.0392156862745098F);
    mcppvp->payload[0] = _voltagePowerBoard;
}

// ================================ ENCODE ================================
static inline void encodeMCP_PowerVoltage(MCP_PowerVoltagePayload *mcppvp, MCP_PowerVoltage *mcppv){
    MCP_PowerVoltage_set_voltagePowerBoard   (mcppvp, mcppv->voltagePowerBoard);
}

// ================================ DECODE ================================
static inline void decodeMCP_PowerVoltage(MCP_PowerVoltage *mcppv, MCP_PowerVoltagePayload *mcppvp){
    mcppv->voltagePowerBoard= MCP_PowerVoltage_get_voltagePowerBoard(mcppvp);
}

#endif /*__MCP_POWER_VOLTAGE_H*/
