// AUTOGENERATED. Run generator/main.py to regenerate
/*
[  0   ]
1111---- mcpVersion
----1--- dribblerEncoderWorking
-----1-- ballsensorWorking
*/

#ifndef __MCP_DRIBBLER_ALIVE_H
#define __MCP_DRIBBLER_ALIVE_H

#include <stdbool.h>
#include <stdint.h>
#include "MCP_BaseTypes.h"

typedef struct _MCP_DribblerAlivePayload {
    uint8_t payload[MCP_PACKET_SIZE_MCP_DRIBBLER_ALIVE];
} MCP_DribblerAlivePayload;

typedef struct _MCP_DribblerAlive {
    uint32_t   mcpVersion          ; // integer [0, 15]              version of mcp
    bool       dribblerEncoderWorking; // integer [0, 1]               status of dribbler encoder
    bool       ballsensorWorking   ; // integer [0, 1]               status of ballsensor
} MCP_DribblerAlive;

// ================================ GETTERS ================================
static inline uint32_t MCP_DribblerAlive_get_mcpVersion(MCP_DribblerAlivePayload *mcpdap){
   return ((mcpdap->payload[0] & 0b11110000) >> 4);
}

static inline bool MCP_DribblerAlive_get_dribblerEncoderWorking(MCP_DribblerAlivePayload *mcpdap){
    return (mcpdap->payload[0] & 0b00001000) > 0;
}

static inline bool MCP_DribblerAlive_get_ballsensorWorking(MCP_DribblerAlivePayload *mcpdap){
    return (mcpdap->payload[0] & 0b00000100) > 0;
}

// ================================ SETTERS ================================
static inline void MCP_DribblerAlive_set_mcpVersion(MCP_DribblerAlivePayload *mcpdap, uint32_t mcpVersion){
    mcpdap->payload[0] = ((mcpVersion << 4) & 0b11110000) | (mcpdap->payload[0] & 0b00001111);
}

static inline void MCP_DribblerAlive_set_dribblerEncoderWorking(MCP_DribblerAlivePayload *mcpdap, bool dribblerEncoderWorking){
    mcpdap->payload[0] = ((dribblerEncoderWorking << 3) & 0b00001000) | (mcpdap->payload[0] & 0b11110111);
}

static inline void MCP_DribblerAlive_set_ballsensorWorking(MCP_DribblerAlivePayload *mcpdap, bool ballsensorWorking){
    mcpdap->payload[0] = ((ballsensorWorking << 2) & 0b00000100) | (mcpdap->payload[0] & 0b11111011);
}

// ================================ ENCODE ================================
static inline void encodeMCP_DribblerAlive(MCP_DribblerAlivePayload *mcpdap, MCP_DribblerAlive *mcpda){
    MCP_DribblerAlive_set_mcpVersion          (mcpdap, mcpda->mcpVersion);
    MCP_DribblerAlive_set_dribblerEncoderWorking(mcpdap, mcpda->dribblerEncoderWorking);
    MCP_DribblerAlive_set_ballsensorWorking   (mcpdap, mcpda->ballsensorWorking);
}

// ================================ DECODE ================================
static inline void decodeMCP_DribblerAlive(MCP_DribblerAlive *mcpda, MCP_DribblerAlivePayload *mcpdap){
    mcpda->mcpVersion    = MCP_DribblerAlive_get_mcpVersion(mcpdap);
    mcpda->dribblerEncoderWorking= MCP_DribblerAlive_get_dribblerEncoderWorking(mcpdap);
    mcpda->ballsensorWorking= MCP_DribblerAlive_get_ballsensorWorking(mcpdap);
}

#endif /*__MCP_DRIBBLER_ALIVE_H*/
