// AUTOGENERATED. Run generator/main.py to regenerate
#ifndef __MCP_TO_TOP_H
#define __MCP_TO_TOP_H

#include "MCP_Ack.h"
#include "MCP_DribblerAlive.h"
#include "MCP_SeesBall.h"
#include "MCP_KickerAlive.h"
#include "MCP_KickerCapacitorVoltage.h"
#include "MCP_KickerStatus.h"
#include "MCP_PowerAlive.h"
#include "MCP_PowerVoltage.h"
#include "MCP_DribblerEncoder.h"
#endif /* __MCP_TO_TOP_H */
