// AUTOGENERATED. Run generator/main.py to regenerate
/*
[  0   ] [  1   ] [  2   ] [  3   ]
11111111 -------- -------- -------- ack_number
-------- 11111111 11111111 -------- dribblerSpeedBefore
-------- -------- -------- 1------- dribblerSeesBall
-------- -------- -------- -1------ ballsensorSeesBall
*/

#ifndef __MCP_SEES_BALL_H
#define __MCP_SEES_BALL_H

#include <stdbool.h>
#include <stdint.h>
#include "MCP_BaseTypes.h"

typedef struct _MCP_SeesBallPayload {
    uint8_t payload[MCP_PACKET_SIZE_MCP_SEES_BALL];
} MCP_SeesBallPayload;

typedef struct _MCP_SeesBall {
    uint32_t   ack_number          ; // integer [0, 255]             acknowledgements
    float      dribblerSpeedBefore ; // float   [0.000, 5000.000]    dribbler speed before it got the ball
    bool       dribblerSeesBall    ; // integer [0, 1]               true if dribbler encoder detects ball
    bool       ballsensorSeesBall  ; // integer [0, 1]               true if ball sensor detects ball
} MCP_SeesBall;

// ================================ GETTERS ================================
static inline uint32_t MCP_SeesBall_get_ack_number(MCP_SeesBallPayload *mcpsbp){
   return ((mcpsbp->payload[0]));
}

static inline float MCP_SeesBall_get_dribblerSpeedBefore(MCP_SeesBallPayload *mcpsbp){
    uint32_t _dribblerSpeedBefore = ((mcpsbp->payload[1]) << 8) | ((mcpsbp->payload[2]));
    return (_dribblerSpeedBefore * 0.0762951094834821F);
}

static inline bool MCP_SeesBall_get_dribblerSeesBall(MCP_SeesBallPayload *mcpsbp){
    return (mcpsbp->payload[3] & 0b10000000) > 0;
}

static inline bool MCP_SeesBall_get_ballsensorSeesBall(MCP_SeesBallPayload *mcpsbp){
    return (mcpsbp->payload[3] & 0b01000000) > 0;
}

// ================================ SETTERS ================================
static inline void MCP_SeesBall_set_ack_number(MCP_SeesBallPayload *mcpsbp, uint32_t ack_number){
    mcpsbp->payload[0] = ack_number;
}

static inline void MCP_SeesBall_set_dribblerSpeedBefore(MCP_SeesBallPayload *mcpsbp, float dribblerSpeedBefore){
    uint32_t _dribblerSpeedBefore = (uint32_t)(dribblerSpeedBefore / 0.0762951094834821F);
    mcpsbp->payload[1] = (_dribblerSpeedBefore >> 8);
    mcpsbp->payload[2] = _dribblerSpeedBefore;
}

static inline void MCP_SeesBall_set_dribblerSeesBall(MCP_SeesBallPayload *mcpsbp, bool dribblerSeesBall){
    mcpsbp->payload[3] = ((dribblerSeesBall << 7) & 0b10000000) | (mcpsbp->payload[3] & 0b01111111);
}

static inline void MCP_SeesBall_set_ballsensorSeesBall(MCP_SeesBallPayload *mcpsbp, bool ballsensorSeesBall){
    mcpsbp->payload[3] = ((ballsensorSeesBall << 6) & 0b01000000) | (mcpsbp->payload[3] & 0b10111111);
}

// ================================ ENCODE ================================
static inline void encodeMCP_SeesBall(MCP_SeesBallPayload *mcpsbp, MCP_SeesBall *mcpsb){
    MCP_SeesBall_set_ack_number          (mcpsbp, mcpsb->ack_number);
    MCP_SeesBall_set_dribblerSpeedBefore (mcpsbp, mcpsb->dribblerSpeedBefore);
    MCP_SeesBall_set_dribblerSeesBall    (mcpsbp, mcpsb->dribblerSeesBall);
    MCP_SeesBall_set_ballsensorSeesBall  (mcpsbp, mcpsb->ballsensorSeesBall);
}

// ================================ DECODE ================================
static inline void decodeMCP_SeesBall(MCP_SeesBall *mcpsb, MCP_SeesBallPayload *mcpsbp){
    mcpsb->ack_number    = MCP_SeesBall_get_ack_number(mcpsbp);
    mcpsb->dribblerSpeedBefore= MCP_SeesBall_get_dribblerSpeedBefore(mcpsbp);
    mcpsb->dribblerSeesBall= MCP_SeesBall_get_dribblerSeesBall(mcpsbp);
    mcpsb->ballsensorSeesBall= MCP_SeesBall_get_ballsensorSeesBall(mcpsbp);
}

#endif /*__MCP_SEES_BALL_H*/
