// AUTOGENERATED. Run generator/main.py to regenerate
#ifndef __MCP_TO_POWER_H
#define __MCP_TO_POWER_H

#include "MCP_Ack.h"
#include "MCP_AreYouAlive.h"
#include "MCP_DribblerAlive.h"
#include "MCP_KickerAlive.h"
#include "MCP_Kill.h"
#include "MCP_StopSending.h"
#endif /* __MCP_TO_POWER_H */
