// AUTOGENERATED. Run generator/main.py to regenerate
#ifndef __MCP_TO_DRIBBLER_H
#define __MCP_TO_DRIBBLER_H

#include "MCP_Ack.h"
#include "MCP_AreYouAlive.h"
#include "MCP_SetDribblerSpeed.h"
#include "MCP_KickerAlive.h"
#include "MCP_PowerAlive.h"
#include "MCP_PowerVoltage.h"
#include "MCP_StopSending.h"
#endif /* __MCP_TO_DRIBBLER_H */
