// AUTOGENERATED. Run generator/main.py to regenerate
#ifndef __MCP_FROM_KICKER_H
#define __MCP_FROM_KICKER_H

#include "MCP_KickerAlive.h"
#include "MCP_KickerCapacitorVoltage.h"
#endif /* __MCP_FROM_KICKER_H */
