// AUTOGENERATED. Run generator/main.py to regenerate
/*

*/

#ifndef __MCP_KILL_H
#define __MCP_KILL_H

#include <stdbool.h>
#include <stdint.h>
#include "MCP_BaseTypes.h"

typedef struct _MCP_KillPayload {
    uint8_t payload[MCP_PACKET_SIZE_MCP_KILL];
} MCP_KillPayload;

typedef struct _MCP_Kill {
} MCP_Kill;

// ================================ GETTERS ================================
// ================================ SETTERS ================================
// ================================ ENCODE ================================
static inline void encodeMCP_Kill(MCP_KillPayload *mcpkp, MCP_Kill *mcpk){
}

// ================================ DECODE ================================
static inline void decodeMCP_Kill(MCP_Kill *mcpk, MCP_KillPayload *mcpkp){
}

#endif /*__MCP_KILL_H*/
