// AUTOGENERATED. Run generator/main.py to regenerate
#ifndef __MCP_FROM_DRIBBLER_H
#define __MCP_FROM_DRIBBLER_H

#include "MCP_Ack.h"
#include "MCP_DribblerAlive.h"
#include "MCP_SeesBall.h"
#include "MCP_DribblerEncoder.h"
#endif /* __MCP_FROM_DRIBBLER_H */
