// AUTOGENERATED. Run generator/main.py to regenerate
/*
[  0   ] [  1   ] [  2   ] [  3   ] [  4   ]
11111111 -------- -------- -------- -------- ack_number
-------- 11111111 11111111 -------- -------- measuredSpeed
-------- -------- -------- 11111111 11111111 filteredSpeed
*/

#ifndef __MCP_DRIBBLER_ENCODER_H
#define __MCP_DRIBBLER_ENCODER_H

#include <stdbool.h>
#include <stdint.h>
#include "MCP_BaseTypes.h"

typedef struct _MCP_DribblerEncoderPayload {
    uint8_t payload[MCP_PACKET_SIZE_MCP_DRIBBLER_ENCODER];
} MCP_DribblerEncoderPayload;

typedef struct _MCP_DribblerEncoder {
    uint32_t   ack_number          ; // integer [0, 255]             acknowledgements
    float      measuredSpeed       ; // float   [0.000, 5000.000]    Measured dribbler speed
    float      filteredSpeed       ; // float   [0.000, 5000.000]    Filtered dribbler speed
} MCP_DribblerEncoder;

// ================================ GETTERS ================================
static inline uint32_t MCP_DribblerEncoder_get_ack_number(MCP_DribblerEncoderPayload *mcpdep){
   return ((mcpdep->payload[0]));
}

static inline float MCP_DribblerEncoder_get_measuredSpeed(MCP_DribblerEncoderPayload *mcpdep){
    uint32_t _measuredSpeed = ((mcpdep->payload[1]) << 8) | ((mcpdep->payload[2]));
    return (_measuredSpeed * 0.0762951094834821F);
}

static inline float MCP_DribblerEncoder_get_filteredSpeed(MCP_DribblerEncoderPayload *mcpdep){
    uint32_t _filteredSpeed = ((mcpdep->payload[3]) << 8) | ((mcpdep->payload[4]));
    return (_filteredSpeed * 0.0762951094834821F);
}

// ================================ SETTERS ================================
static inline void MCP_DribblerEncoder_set_ack_number(MCP_DribblerEncoderPayload *mcpdep, uint32_t ack_number){
    mcpdep->payload[0] = ack_number;
}

static inline void MCP_DribblerEncoder_set_measuredSpeed(MCP_DribblerEncoderPayload *mcpdep, float measuredSpeed){
    uint32_t _measuredSpeed = (uint32_t)(measuredSpeed / 0.0762951094834821F);
    mcpdep->payload[1] = (_measuredSpeed >> 8);
    mcpdep->payload[2] = _measuredSpeed;
}

static inline void MCP_DribblerEncoder_set_filteredSpeed(MCP_DribblerEncoderPayload *mcpdep, float filteredSpeed){
    uint32_t _filteredSpeed = (uint32_t)(filteredSpeed / 0.0762951094834821F);
    mcpdep->payload[3] = (_filteredSpeed >> 8);
    mcpdep->payload[4] = _filteredSpeed;
}

// ================================ ENCODE ================================
static inline void encodeMCP_DribblerEncoder(MCP_DribblerEncoderPayload *mcpdep, MCP_DribblerEncoder *mcpde){
    MCP_DribblerEncoder_set_ack_number          (mcpdep, mcpde->ack_number);
    MCP_DribblerEncoder_set_measuredSpeed       (mcpdep, mcpde->measuredSpeed);
    MCP_DribblerEncoder_set_filteredSpeed       (mcpdep, mcpde->filteredSpeed);
}

// ================================ DECODE ================================
static inline void decodeMCP_DribblerEncoder(MCP_DribblerEncoder *mcpde, MCP_DribblerEncoderPayload *mcpdep){
    mcpde->ack_number    = MCP_DribblerEncoder_get_ack_number(mcpdep);
    mcpde->measuredSpeed = MCP_DribblerEncoder_get_measuredSpeed(mcpdep);
    mcpde->filteredSpeed = MCP_DribblerEncoder_get_filteredSpeed(mcpdep);
}

#endif /*__MCP_DRIBBLER_ENCODER_H*/
