// AUTOGENERATED. Run generator/main.py to regenerate
/*
[  0   ] [  1   ]
11111111 -------- ack_number
-------- 11111111 shootPower
*/

#ifndef __MCP_KICK_H
#define __MCP_KICK_H

#include <stdbool.h>
#include <stdint.h>
#include "MCP_BaseTypes.h"

typedef struct _MCP_KickPayload {
    uint8_t payload[MCP_PACKET_SIZE_MCP_KICK];
} MCP_KickPayload;

typedef struct _MCP_Kick {
    uint32_t   ack_number          ; // integer [0, 255]             acknowledgements
    float      shootPower          ; // float   [0.000, 6.500]       desired speed of the ball
} MCP_Kick;

// ================================ GETTERS ================================
static inline uint32_t MCP_Kick_get_ack_number(MCP_KickPayload *mcpkp){
   return ((mcpkp->payload[0]));
}

static inline float MCP_Kick_get_shootPower(MCP_KickPayload *mcpkp){
    uint32_t _shootPower = ((mcpkp->payload[1]));
    return (_shootPower * 0.0254901960784314F);
}

// ================================ SETTERS ================================
static inline void MCP_Kick_set_ack_number(MCP_KickPayload *mcpkp, uint32_t ack_number){
    mcpkp->payload[0] = ack_number;
}

static inline void MCP_Kick_set_shootPower(MCP_KickPayload *mcpkp, float shootPower){
    uint32_t _shootPower = (uint32_t)(shootPower / 0.0254901960784314F);
    mcpkp->payload[1] = _shootPower;
}

// ================================ ENCODE ================================
static inline void encodeMCP_Kick(MCP_KickPayload *mcpkp, MCP_Kick *mcpk){
    MCP_Kick_set_ack_number          (mcpkp, mcpk->ack_number);
    MCP_Kick_set_shootPower          (mcpkp, mcpk->shootPower);
}

// ================================ DECODE ================================
static inline void decodeMCP_Kick(MCP_Kick *mcpk, MCP_KickPayload *mcpkp){
    mcpk->ack_number     = MCP_Kick_get_ack_number(mcpkp);
    mcpk->shootPower     = MCP_Kick_get_shootPower(mcpkp);
}

#endif /*__MCP_KICK_H*/
