// AUTOGENERATED. Run generator/main.py to regenerate
#ifndef __MCP_TO_KICKER_H
#define __MCP_TO_KICKER_H

#include "MCP_AreYouAlive.h"
#include "MCP_KickerCharge.h"
#include "MCP_KickerStopCharge.h"
#include "MCP_Kick.h"
#include "MCP_Chip.h"
#endif /* __MCP_TO_KICKER_H */
