name: PlatformIO Build

on: 
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  
jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      
    - name: Fetch REM
      uses: snickerbockers/submodules-init@v4
      
    - name: Run PlatformIO
      uses: karniv00l/platformio-run-action@v1.1.1
      with:
        verbose: true
      
